# 💖 Sponsorship configuration for Knoph Ayieko

github: [Knoph1]   # GitHub Sponsors username

# Optional external funding platforms
patreon:            # No Patreon set (can add later if you open one)
open_collective:    # No Open Collective currently
ko_fi: knoph        # Your Ko-fi handle (if you claim it)
tidelift:           # No Tidelift package yet
community_bridge:   # Not using Community Bridge
liberapay:          # Add here if you create one
issuehunt:          # Not set
lfx_crowdfunding:   # Not set
polar:              # Not set
buy_me_a_coffee: knoph   # Your Buy Me a Coffee handle (if claimed)
thanks_dev:         # Not set

# Custom external links (can be up to 4)
custom:
  - "https://www.knoph.dev"
  - "https://github.com/sponsors/Knoph1"
  - "https://www.linkedin.com/in/knoph-ayieko"
  - "https://orcid.org/0009-0001-3787-513X"
