name: Update GitHub Stats

on:
  schedule:
    - cron: "0 6 * * *" # Runs daily at 06:00 UTC = 09:00 EAT
  workflow_dispatch: # Allow manual trigger

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run stats script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: Knoph1
        run: python stats.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add STATS.md
          git commit -m "chore: update repo stats [skip ci]" || echo "No changes to commit"
          git push
